name: Build dev version
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for changelog generation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser (Snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binaries
          path: dist/**/gocast
